name: MSYS2
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '⬛', sys: mingw32 }
          - { icon: '🟦', sys: mingw64 }
    name: 🚧${{ matrix.icon }} ${{ matrix.sys }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: '${{ matrix.icon }} Setup MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            git
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
            openssl:p
                     
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=install -DBUILD_SHARED_LIBS=on -DANALYZER=off -DSANITIZER=none -DENABLE_SSL=on -DENABLE_SECURITY=on -DENABLE_LIFESPAN=on -DENABLE_DEADLINE_MISSED=on '-DSKIP_DEADLINE_UPDATE=off' -DENABLE_TYPELIB=on -DENABLE_TYPE_DISCOVERY=on -DENABLE_TOPIC_DISCOVERY=on -DENABLE_COVERAGE=off -DENABLE_ICEORYX=off -DBUILD_TESTING=on -DBUILD_IDLC_XTESTS=off -DBUILD_EXAMPLES=on -DWERROR=on -G 'MinGW Makefiles' -A '' -T '' ..